### ISSUE TITLE
Heroku deployment does not work - can not load buildXX.main.js files

### ISSUE THREAD

**Issue by codeaside** [jfarid27/h4kr#8]
Hi, sorry to bug you this way, I tried to use your heroku deployment and it can not connect to MetaMask:

Looks like it maybe expects different deployment filenames? 
Happens on both Chrome and Firefox, also cleared the FF cache:

GET https://hackmoney-crypto.herokuapp.com/dist/build20.main.js [HTTP/1.1 404 Not Found 116ms]
GET https://hackmoney-crypto.herokuapp.com/dist/build38.main.js [HTTP/1.1 404 Not Found 518ms]
GET https://hackmoney-crypto.herokuapp.com/dist/build30.main.js [HTTP/1.1 404 Not Found 542ms]
GET https://hackmoney-crypto.herokuapp.com/dist/build33.main.js [HTTP/1.1 404 Not Found 214ms]

Load failed for <script> with source "https://hackmoney-crypto.herokuapp.com/dist/build20.main.js". hackmoney-crypto.herokuapp.com:1:1
Uncaught (in promise) ChunkLoadError: Loading chunk 20 failed.
(error: https://hackmoney-crypto.herokuapp.com/dist/build20.main.js)
    Webpack 32
bootstrap:105:17
Load failed for <script> with source "https://hackmoney-crypto.herokuapp.com/dist/build33.main.js". hackmoney-crypto.herokuapp.com:1:1
Uncaught (in promise) ChunkLoadError: Loading chunk 33 failed.
(error: https://hackmoney-crypto.herokuapp.com/dist/build33.main.js)
    Webpack 41
bootstrap:105:17
Load failed for <script> with source "https://hackmoney-crypto.herokuapp.com/dist/build38.main.js". hackmoney-crypto.herokuapp.com:1:1
Load failed for <script> with source "https://hackmoney-crypto.herokuapp.com/dist/build30.main.js". hackmoney-crypto.herokuapp.com:1:1

​Thanks!

**Comment by jfarid27** [comment]
@codeaside This might be the issue 49f00b47585f015f370861525aae1a29584240d8. Maybe webpack doesn't like the slash. These days I don't really deploy on production and run this app locally.
